export enum CashExpenseCategoryDto {
  SERVICIOS_BASICOS = 'SERVICIOS_BASICOS',
  INSUMOS_URGENTES = 'INSUMOS_URGENTES',
  LIMPIEZA_MANTENIMIENTO = 'LIMPIEZA_MANTENIMIENTO',
  PAGO_PROVEEDOR = 'PAGO_PROVEEDOR',
  ADELANTO_SUELDO = 'ADELANTO_SUELDO',
  TRANSPORTE_FLETE = 'TRANSPORTE_FLETE',
  OTROS = 'OTROS',
}
